"""
WhatsApp-style Emoji System with 8 Categories
Provides structured emoji data with UTF-8 support and proper categorization
"""

from typing import List, Dict, Any, Optional
from datetime import datetime, timezone

# WhatsApp-style emoji categories with official Unicode values
EMOJI_CATEGORIES = {
    "Smileys & People": [
        {"name": "Grinning Face", "symbol": "😀", "unicode": "U+1F600"},
        {"name": "Grinning Face with Big Eyes", "symbol": "😃", "unicode": "U+1F603"},
        {"name": "Grinning Face with Smiling Eyes", "symbol": "😄", "unicode": "U+1F604"},
        {"name": "Beaming Face with Smiling Eyes", "symbol": "😁", "unicode": "U+1F601"},
        {"name": "Grinning Squinting Face", "symbol": "😆", "unicode": "U+1F606"},
        {"name": "Grinning Face with Sweat", "symbol": "😅", "unicode": "U+1F605"},
        {"name": "Rolling on the Floor Laughing", "symbol": "🤣", "unicode": "U+1F923"},
        {"name": "Face with Tears of Joy", "symbol": "😂", "unicode": "U+1F602"},
        {"name": "Slightly Smiling Face", "symbol": "🙂", "unicode": "U+1F642"},
        {"name": "Upside-Down Face", "symbol": "🙃", "unicode": "U+1F643"},
        {"name": "Winking Face", "symbol": "😉", "unicode": "U+1F609"},
        {"name": "Smiling Face with Smiling Eyes", "symbol": "😊", "unicode": "U+1F60A"},
        {"name": "Smiling Face with Halo", "symbol": "😇", "unicode": "U+1F607"},
        {"name": "Smiling Face with Hearts", "symbol": "🥰", "unicode": "U+1F970"},
        {"name": "Smiling Face with Tear", "symbol": "🥲", "unicode": "U+1F972"},
        {"name": "Relieved Face", "symbol": "😌", "unicode": "U+1F60C"},
        {"name": "Smiling Face with Sunglasses", "symbol": "😎", "unicode": "U+1F60E"},
        {"name": "Smirking Face", "symbol": "😏", "unicode": "U+1F60F"},
        {"name": "Neutral Face", "symbol": "😐", "unicode": "U+1F610"},
        {"name": "Expressionless Face", "symbol": "😑", "unicode": "U+1F611"},
        {"name": "Unamused Face", "symbol": "😒", "unicode": "U+1F612"},
        {"name": "Face with Rolling Eyes", "symbol": "🙄", "unicode": "U+1F644"},
        {"name": "Thinking Face", "symbol": "🤔", "unicode": "U+1F914"},
        {"name": "Lying Face", "symbol": "🤥", "unicode": "U+1F925"},
        {"name": "Hand over Mouth", "symbol": "🤭", "unicode": "U+1F92D"},
        {"name": "Shushing Face", "symbol": "🤫", "unicode": "U+1F92B"},
        {"name": "Face with Monocle", "symbol": "🧐", "unicode": "U+1F9D0"},
        {"name": "Face with Raised Eyebrow", "symbol": "🤨", "unicode": "U+1F928"},
        {"name": "Face with Mouth Open", "symbol": "😮", "unicode": "U+1F62E"},
        {"name": "Astonished Face", "symbol": "😲", "unicode": "U+1F632"},
        {"name": "Frowning Face with Open Mouth", "symbol": "😧", "unicode": "U+1F627"},
        {"name": "Anguished Face", "symbol": "😨", "unicode": "U+1F628"},
        {"name": "Anxious Face with Sweat", "symbol": "😰", "unicode": "U+1F630"},
        {"name": "Sad but Relieved Face", "symbol": "😥", "unicode": "U+1F625"},
        {"name": "Crying Face", "symbol": "😢", "unicode": "U+1F622"},
        {"name": "Loudly Crying Face", "symbol": "😭", "unicode": "U+1F62D"},
        {"name": "Face Screaming in Fear", "symbol": "😱", "unicode": "U+1F631"},
        {"name": "Confounded Face", "symbol": "😖", "unicode": "U+1F616"},
        {"name": "Persevering Face", "symbol": "😣", "unicode": "U+1F623"},
        {"name": "Disappointed Face", "symbol": "😞", "unicode": "U+1F61E"},
        {"name": "Downcast Face with Sweat", "symbol": "😓", "unicode": "U+1F613"},
        {"name": "Pleading Face", "symbol": "🥺", "unicode": "U+1F97A"},
        {"name": "Woozy Face", "symbol": "🥴", "unicode": "U+1F974"},
        {"name": "Exploding Head", "symbol": "🤯", "unicode": "U+1F92F"},
        {"name": "Cowboy Hat Face", "symbol": "🤠", "unicode": "U+1F920"},
        {"name": "Clown Face", "symbol": "🤡", "unicode": "U+1F921"},
        {"name": "Nauseated Face", "symbol": "🤢", "unicode": "U+1F922"},
        {"name": "Vomiting Face", "symbol": "🤮", "unicode": "U+1F92E"},
        {"name": "Sneezing Face", "symbol": "🤧", "unicode": "U+1F927"},
        {"name": "Hot Face", "symbol": "🥵", "unicode": "U+1F975"},
        {"name": "Cold Face", "symbol": "🥶", "unicode": "U+1F976"},
        {"name": "Party Popper", "symbol": "🎉", "unicode": "U+1F389"},
        {"name": "Confetti Ball", "symbol": "🎊", "unicode": "U+1F38A"},
        {"name": "Kissing Face", "symbol": "😗", "unicode": "U+1F617"},
        {"name": "Kissing Face with Smiling Eyes", "symbol": "😙", "unicode": "U+1F619"},
        {"name": "Kissing Face with Closed Eyes", "symbol": "😚", "unicode": "U+1F61A"},
        {"name": "Face Blowing a Kiss", "symbol": "😘", "unicode": "U+1F618"},
        {"name": "Love-Heart Letter", "symbol": "💌", "unicode": "U+1F48C"},
        {"name": "Heart with Arrow", "symbol": "💘", "unicode": "U+1F498"},
        {"name": "Heart with Ribbon", "symbol": "💝", "unicode": "U+1F49D"},
        {"name": "Sparkling Heart", "symbol": "💖", "unicode": "U+1F496"},
        {"name": "Growing Heart", "symbol": "💗", "unicode": "U+1F497"},
        {"name": "Beating Heart", "symbol": "💓", "unicode": "U+1F493"},
        {"name": "Revolving Hearts", "symbol": "💞", "unicode": "U+1F49E"},
        {"name": "Two Hearts", "symbol": "💕", "unicode": "U+1F495"},
        {"name": "Heart Decoration", "symbol": "💟", "unicode": "U+1F49F"},
        {"name": "Heavy Heart Exclamation", "symbol": "❣️", "unicode": "U+2763"},
        {"name": "Broken Heart", "symbol": "💔", "unicode": "U+1F494"},
        {"name": "Red Heart", "symbol": "❤️", "unicode": "U+2764"},
        {"name": "Orange Heart", "symbol": "🧡", "unicode": "U+1F9E1"},
        {"name": "Yellow Heart", "symbol": "💛", "unicode": "U+1F49B"},
        {"name": "Green Heart", "symbol": "💚", "unicode": "U+1F49A"},
        {"name": "Blue Heart", "symbol": "💙", "unicode": "U+1F499"},
        {"name": "Purple Heart", "symbol": "💜", "unicode": "U+1F49C"},
        {"name": "Brown Heart", "symbol": "🤎", "unicode": "U+1F90E"},
        {"name": "Black Heart", "symbol": "🖤", "unicode": "U+1F5A4"},
        {"name": "White Heart", "symbol": "🤍", "unicode": "U+1F90D"},
        {"name": "Hugging Face", "symbol": "🤗", "unicode": "U+1F917"},
        {"name": "Saluting Face", "symbol": "🫡", "unicode": "U+1FAE1"},
        {"name": "Face with Peeking Eye", "symbol": "🫣", "unicode": "U+1FAE3"},
        {"name": "Face with Diagonal Mouth", "symbol": "🫤", "unicode": "U+1FAE4"},
        {"name": "Dotted Line Face", "symbol": "🫥", "unicode": "U+1FAE5"},
        {"name": "Head Shaking Vertically", "symbol": "🫨", "unicode": "U+1FAE8"},
        {"name": "Head Shaking Horizontally", "symbol": "🫠", "unicode": "U+1FAE9"},
        {"name": "Thumbs Up", "symbol": "👍", "unicode": "U+1F44D"},
        {"name": "Thumbs Down", "symbol": "👎", "unicode": "U+1F44E"},
        {"name": "Clapping Hands", "symbol": "👏", "unicode": "U+1F44F"},
        {"name": "Raising Hands", "symbol": "🙌", "unicode": "U+1F64C"},
        {"name": "Open Hands", "symbol": "👐", "unicode": "U+1F450"},
        {"name": "Palms Up Together", "symbol": "🤲", "unicode": "U+1F932"},
        {"name": "Handshake", "symbol": "🤝", "unicode": "U+1F91D"},
        {"name": "Folded Hands", "symbol": "🙏", "unicode": "U+1F64F"},
        {"name": "Writing Hand", "symbol": "✍️", "unicode": "U+270D"},
        {"name": "Nail Polish", "symbol": "💅", "unicode": "U+1F485"},
        {"name": "Selfie", "symbol": "🤳", "unicode": "U+1F933"},
        {"name": "Flexed Biceps", "symbol": "💪", "unicode": "U+1F4AA"},
        {"name": "Mechanical Arm", "symbol": "🦾", "unicode": "U+1F9BE"},
        {"name": "Mechanical Leg", "symbol": "🦿", "unicode": "U+1F9BF"},
        {"name": "Leg", "symbol": "🦵", "unicode": "U+1F9B5"},
        {"name": "Foot", "symbol": "🦶", "unicode": "U+1F9B6"},
        {"name": "Ear", "symbol": "👂", "unicode": "U+1F442"},
        {"name": "Ear with Hearing Aid", "symbol": "🦻", "unicode": "U+1F9BB"},
        {"name": "Nose", "symbol": "👃", "unicode": "U+1F443"},
        {"name": "Brain", "symbol": "🧠", "unicode": "U+1F9E0"},
        {"name": "Lungs", "symbol": "🫁", "unicode": "U+1FAE1"},
        {"name": "Tooth", "symbol": "🦷", "unicode": "U+1F9B7"},
        {"name": "Bone", "symbol": "🦴", "unicode": "U+1F9B4"},
        {"name": "Eye", "symbol": "👁️", "unicode": "U+1F441"},
        {"name": "Tongue", "symbol": "👅", "unicode": "U+1F445"},
        {"name": "Mouth", "symbol": "👄", "unicode": "U+1F444"},
        {"name": "Smiling Face Halo", "symbol": "☺️", "unicode": "U+263A"},
        {"name": "Grinning Face Ears", "symbol": "🐵", "unicode": "U+1F435"},
        {"name": "Monkey", "symbol": "🐒", "unicode": "U+1F412"},
        {"name": "Gorilla", "symbol": "🦍", "unicode": "U+1F98D"},
        {"name": "Orangutan", "symbol": "🦧", "unicode": "U+1F9A7"},
        {"name": "Baby", "symbol": "👶", "unicode": "U+1F476"},
        {"name": "Child", "symbol": "🧒", "unicode": "U+1F9D2"},
        {"name": "Boy", "symbol": "👦", "unicode": "U+1F466"},
        {"name": "Girl", "symbol": "👧", "unicode": "U+1F467"},
        {"name": "Adult", "symbol": "🧑", "unicode": "U+1F9D1"},
        {"name": "Person with Blond Hair", "symbol": "👱", "unicode": "U+1F471"},
        {"name": "Man", "symbol": "👨", "unicode": "U+1F468"},
        {"name": "Woman", "symbol": "👩", "unicode": "U+1F469"},
        {"name": "Older Adult", "symbol": "🧓", "unicode": "U+1F9D3"},
        {"name": "Older Man", "symbol": "👴", "unicode": "U+1F474"},
        {"name": "Older Woman", "symbol": "👵", "unicode": "U+1F475"},
        {"name": "Person with Skirt", "symbol": "🚶‍♀️", "unicode": "U+1F6B6"},
        {"name": "Person with Probing Cane", "symbol": "🧑‍🦯", "unicode": "U+1F9D1"},
        {"name": "Person Gesturing No", "symbol": "🙅", "unicode": "U+1F645"},
        {"name": "Person Gesturing OK", "symbol": "🙆", "unicode": "U+1F646"},
        {"name": "Person Bowing", "symbol": "🙇", "unicode": "U+1F647"},
        {"name": "Person Cartwheeling", "symbol": "🤸", "unicode": "U+1F938"},
        {"name": "Person Playing Handball", "symbol": "🤾", "unicode": "U+1F93E"},
        {"name": "Person Climbing", "symbol": "🧗", "unicode": "U+1F9D7"},
        {"name": "Person in Steamy Room", "symbol": "🧖", "unicode": "U+1F9D6"},
        {"name": "Person Facepalming", "symbol": "🤦", "unicode": "U+1F926"},
        {"name": "Person Shrugging", "symbol": "🤷", "unicode": "U+1F937"},
        {"name": "Health Worker", "symbol": "🧑‍⚕️", "unicode": "U+1F9D1"},
        {"name": "Judge", "symbol": "🧑‍⚖️", "unicode": "U+1F9D1"},
        {"name": "Farmer", "symbol": "🧑‍🌾", "unicode": "U+1F9D1"},
        {"name": "Cook", "symbol": "🧑‍🍳", "unicode": "U+1F9D1"},
        {"name": "Student", "symbol": "🧑‍🎓", "unicode": "U+1F9D1"},
        {"name": "Thumbs Up Light Skin", "symbol": "👍🏻", "unicode": "U+1F44D"},
        {"name": "Thumbs Up Medium Light Skin", "symbol": "👍🏼", "unicode": "U+1F44D"},
        {"name": "Thumbs Up Medium Skin", "symbol": "👍🏽", "unicode": "U+1F44D"},
        {"name": "Thumbs Up Medium Dark Skin", "symbol": "👍🏾", "unicode": "U+1F44D"},
        {"name": "Thumbs Up Dark Skin", "symbol": "👍🏿", "unicode": "U+1F44D"},
        {"name": "Victory Hand Light Skin", "symbol": "✌🏻", "unicode": "U+270C"},
        {"name": "Victory Hand Medium Light Skin", "symbol": "✌🏼", "unicode": "U+270C"},
        {"name": "Victory Hand Medium Skin", "symbol": "✌🏽", "unicode": "U+270C"},
        {"name": "Victory Hand Medium Dark Skin", "symbol": "✌🏾", "unicode": "U+270C"},
        {"name": "Victory Hand Dark Skin", "symbol": "✌🏿", "unicode": "U+270C"},
        {"name": "Waving Hand Light Skin", "symbol": "👋🏻", "unicode": "U+1F44B"},
        {"name": "Waving Hand Medium Light Skin", "symbol": "👋🏼", "unicode": "U+1F44B"},
        {"name": "Waving Hand Medium Skin", "symbol": "👋🏽", "unicode": "U+1F44B"},
        {"name": "Waving Hand Medium Dark Skin", "symbol": "👋🏾", "unicode": "U+1F44B"},
        {"name": "Waving Hand Dark Skin", "symbol": "👋🏿", "unicode": "U+1F44B"},
        {"name": "OK Hand Light Skin", "symbol": "👌🏻", "unicode": "U+1F44C"},
        {"name": "OK Hand Medium Light Skin", "symbol": "👌🏼", "unicode": "U+1F44C"},
        {"name": "OK Hand Medium Skin", "symbol": "👌🏽", "unicode": "U+1F44C"},
        {"name": "OK Hand Medium Dark Skin", "symbol": "👌🏾", "unicode": "U+1F44C"},
        {"name": "OK Hand Dark Skin", "symbol": "👌🏿", "unicode": "U+1F44C"},
        {"name": "Raised Fist Light Skin", "symbol": "✊🏻", "unicode": "U+270A"},
        {"name": "Raised Fist Medium Light Skin", "symbol": "✊🏼", "unicode": "U+270A"},
        {"name": "Raised Fist Medium Skin", "symbol": "✊🏽", "unicode": "U+270A"},
        {"name": "Raised Fist Medium Dark Skin", "symbol": "✊🏾", "unicode": "U+270A"},
        {"name": "Raised Fist Dark Skin", "symbol": "✊🏿", "unicode": "U+270A"},
        {"name": "Pointed Finger Light Skin", "symbol": "☝🏻", "unicode": "U+261D"},
        {"name": "Pointed Finger Medium Light Skin", "symbol": "☝🏼", "unicode": "U+261D"},
        {"name": "Pointed Finger Medium Skin", "symbol": "☝🏽", "unicode": "U+261D"},
        {"name": "Pointed Finger Medium Dark Skin", "symbol": "☝🏾", "unicode": "U+261D"},
        {"name": "Pointed Finger Dark Skin", "symbol": "☝🏿", "unicode": "U+261D"},
        {"name": "Love You Gesture", "symbol": "🤟", "unicode": "U+1F91F"},
        {"name": "Metal Hand", "symbol": "🤘", "unicode": "U+1F918"},
        {"name": "Crossed Fingers", "symbol": "🤞", "unicode": "U+1F91E"},
        {"name": "Call Me Hand", "symbol": "🤙", "unicode": "U+1F919"},
        {"name": "Person Tipping Hand", "symbol": "💁", "unicode": "U+1F481"},
        {"name": "Person Raising Hand", "symbol": "🙋", "unicode": "U+1F64B"},
        {"name": "Person Pouting", "symbol": "🙎", "unicode": "U+1F64E"},
    ],
    
    "Animal & Nature": [
        {"name": "Dog Face", "symbol": "🐕", "unicode": "U+1F415"},
        {"name": "Cat Face", "symbol": "🐈", "unicode": "U+1F408"},
        {"name": "Mouse Face", "symbol": "🐭", "unicode": "U+1F42D"},
        {"name": "Hamster Face", "symbol": "🐹", "unicode": "U+1F439"},
        {"name": "Rabbit Face", "symbol": "🐰", "unicode": "U+1F430"},
        {"name": "Fox Face", "symbol": "🦊", "unicode": "U+1F98A"},
        {"name": "Bear Face", "symbol": "🐻", "unicode": "U+1F43B"},
        {"name": "Panda Face", "symbol": "🐼", "unicode": "U+1F43C"},
        {"name": "Koala Face", "symbol": "🐨", "unicode": "U+1F428"},
        {"name": "Tiger Face", "symbol": "🐯", "unicode": "U+1F42F"},
        {"name": "Lion Face", "symbol": "🦁", "unicode": "U+1F981"},
        {"name": "Cow Face", "symbol": "🐮", "unicode": "U+1F42E"},
        {"name": "Pig Face", "symbol": "🐷", "unicode": "U+1F437"},
        {"name": "Pig Nose", "symbol": "🐽", "unicode": "U+1F43D"},
        {"name": "Frog Face", "symbol": "🐸", "unicode": "U+1F438"},
        {"name": "Chicken", "symbol": "🐔", "unicode": "U+1F414"},
        {"name": "Penguin", "symbol": "🐧", "unicode": "U+1F427"},
        {"name": "Bird", "symbol": "🐦", "unicode": "U+1F426"},
        {"name": "Baby Chick", "symbol": "🐤", "unicode": "U+1F424"},
        {"name": "Hatching Chick", "symbol": "🐣", "unicode": "U+1F423"},
        {"name": "Eagle", "symbol": "🦅", "unicode": "U+1F985"},
        {"name": "Duck", "symbol": "🦆", "unicode": "U+1F986"},
        {"name": "Owl", "symbol": "🦉", "unicode": "U+1F989"},
        {"name": "Bat", "symbol": "🦇", "unicode": "U+1F987"},
        {"name": "Wolf", "symbol": "🐺", "unicode": "U+1F43A"},
        {"name": "Boar", "symbol": "🐗", "unicode": "U+1F417"},
        {"name": "Horse Face", "symbol": "🐴", "unicode": "U+1F434"},
        {"name": "Unicorn", "symbol": "🦄", "unicode": "U+1F984"},
        {"name": "Honeybee", "symbol": "🐝", "unicode": "U+1F41D"},
        {"name": "Bug", "symbol": "🐛", "unicode": "U+1F41B"},
        {"name": "Butterfly", "symbol": "🦋", "unicode": "U+1F98B"},
        {"name": "Snail", "symbol": "🐌", "unicode": "U+1F40C"},
        {"name": "Beetle", "symbol": "🪲", "unicode": "U+1FA92"},
        {"name": "Ant", "symbol": "🐜", "unicode": "U+1F41C"},
        {"name": "Grasshopper", "symbol": "🦗", "unicode": "U+1F97F"},
        {"name": "Spider", "symbol": "🕷️", "unicode": "U+1F577"},
        {"name": "Spider Web", "symbol": "🕸️", "unicode": "U+1F578"},
        {"name": "Scorpion", "symbol": "🦂", "unicode": "U+1F980"},
        {"name": "Mosquito", "symbol": "🦟", "unicode": "U+1F99F"},
        {"name": "Fly", "symbol": "🪰", "unicode": "U+1FAF0"},
        {"name": "Worm", "symbol": "🪱", "unicode": "U+1FAF1"},
        {"name": "Microbe", "symbol": "🦠", "unicode": "U+1F9A0"},
        {"name": "Shell", "symbol": "🐚", "unicode": "U+1F41A"},
        {"name": "Shark", "symbol": "🦈", "unicode": "U+1F988"},
        {"name": "Octopus", "symbol": "🐙", "unicode": "U+1F419"},
        {"name": "Squid", "symbol": "🦑", "unicode": "U+1F991"},
        {"name": "Shrimp", "symbol": "🦐", "unicode": "U+1F990"},
        {"name": "Crab", "symbol": "🦀", "unicode": "U+1F980"},
        {"name": "Lobster", "symbol": "🦞", "unicode": "U+1F99E"},
        {"name": "Tropical Fish", "symbol": "🐠", "unicode": "U+1F420"},
        {"name": "Blowfish", "symbol": "🐡", "unicode": "U+1F421"},
        {"name": "Whale", "symbol": "🐋", "unicode": "U+1F40B"},
        {"name": "Whale Spouting", "symbol": "🐳", "unicode": "U+1F433"},
        {"name": "Dolphin", "symbol": "🐬", "unicode": "U+1F42C"},
        {"name": "Seal", "symbol": "🦭", "unicode": "U+1F9ED"},
        {"name": "Otter", "symbol": "🦦", "unicode": "U+1F9A6"},
        {"name": "Polar Bear", "symbol": "🐻‍❄️", "unicode": "U+1F43B"},
        {"name": "Elephant", "symbol": "🐘", "unicode": "U+1F418"},
        {"name": "Giraffe", "symbol": "🦒", "unicode": "U+1F992"},
        {"name": "Zebra", "symbol": "🦓", "unicode": "U+1F993"},
        {"name": "Hippopotamus", "symbol": "🦛", "unicode": "U+1F99B"},
        {"name": "Rhinoceros", "symbol": "🦏", "unicode": "U+1F98F"},
        {"name": "Kangaroo", "symbol": "🦘", "unicode": "U+1F998"},
        {"name": "Badger", "symbol": "🦡", "unicode": "U+1F9A1"},
        {"name": "Llama", "symbol": "🦙", "unicode": "U+1F999"},
        {"name": "Camel", "symbol": "🐪", "unicode": "U+1F42A"},
        {"name": "Dromedary Camel", "symbol": "🐫", "unicode": "U+1F42B"},
        {"name": "Dragon", "symbol": "🐉", "unicode": "U+1F409"},
        {"name": "Dragon Face", "symbol": "🐲", "unicode": "U+1F432"},
        {"name": "Sauropod", "symbol": "🦕", "unicode": "U+1F995"},
        {"name": "T-Rex", "symbol": "🦖", "unicode": "U+1F996"},
        {"name": "Sloth", "symbol": "🦥", "unicode": "U+1F9A5"},
        {"name": "Skunk", "symbol": "🦨", "unicode": "U+1F9A8"},
        {"name": "Firefly", "symbol": "✨", "unicode": "U+2728"},
        {"name": "Cockroach", "symbol": "🪳", "unicode": "U+1FAF3"},
        {"name": "Coconut", "symbol": "🥥", "unicode": "U+1F965"},
        {"name": "Palm Tree", "symbol": "🌴", "unicode": "U+1F334"},
        {"name": "Evergreen Tree", "symbol": "🌲", "unicode": "U+1F332"},
        {"name": "Deciduous Tree", "symbol": "🌳", "unicode": "U+1F333"},
        {"name": "Cactus", "symbol": "🌵", "unicode": "U+1F335"},
        {"name": "Seedling", "symbol": "🌱", "unicode": "U+1F331"},
        {"name": "Herb", "symbol": "🌿", "unicode": "U+1F3F3"},
        {"name": "Shamrock", "symbol": "🍀", "unicode": "U+1F340"},
        {"name": "Leaf Fluttering in Wind", "symbol": "🍃", "unicode": "U+1F343"},
        {"name": "Rosette Flower", "symbol": "🌹", "unicode": "U+1F339"},
        {"name": "Tulip", "symbol": "🌷", "unicode": "U+1F337"},
        {"name": "Hibiscus", "symbol": "🌺", "unicode": "U+1F33A"},
        {"name": "Sunflower", "symbol": "🌻", "unicode": "U+1F33B"},
        {"name": "Blossom", "symbol": "🌼", "unicode": "U+1F33C"},
        {"name": "Cherry Blossom", "symbol": "🌸", "unicode": "U+1F338"},
        {"name": "Bouquet", "symbol": "💐", "unicode": "U+1F490"},
        {"name": "Corn", "symbol": "🌽", "unicode": "U+1F33D"},
        {"name": "Ear of Rice", "symbol": "🌾", "unicode": "U+1F33E"},
        {"name": "Potted Plant", "symbol": "🪴", "unicode": "U+1FAB4"},
        {"name": "Beetle", "symbol": "🐞", "unicode": "U+1F41E"},
        {"name": "Snake", "symbol": "🐍", "unicode": "U+1F40D"},
        {"name": "Lizard", "symbol": "🦎", "unicode": "U+1F98E"},
        {"name": "Turtle", "symbol": "🐢", "unicode": "U+1F422"},
        {"name": "Crocodile", "symbol": "🐊", "unicode": "U+1F40A"},
        {"name": "Leopard", "symbol": "🐆", "unicode": "U+1F406"},
        {"name": "Tiger", "symbol": "😺", "unicode": "U+1F63A"},
        {"name": "Peacock", "symbol": "🦚", "unicode": "U+1F99A"},
        {"name": "Parrot", "symbol": "🦜", "unicode": "U+1F99C"},
        {"name": "Swan", "symbol": "🦢", "unicode": "U+1F9A2"},
        {"name": "Hummingbird", "symbol": "🕊️", "unicode": "U+1F54A"},
        {"name": "Flamingo", "symbol": "🦩", "unicode": "U+1F9A9"},
        {"name": "Rabbit", "symbol": "🐇", "unicode": "U+1F407"},
        {"name": "Squirrel", "symbol": "🐿️", "unicode": "U+1F43F"},
        {"name": "Beaver", "symbol": "🦫", "unicode": "U+1F9AB"},
        {"name": "Hedgehog", "symbol": "🦔", "unicode": "U+1F994"},
        {"name": "Bat", "symbol": "🦇", "unicode": "U+1F987"},
        {"name": "Otter", "symbol": "🦦", "unicode": "U+1F9A6"},
        {"name": "Skunk", "symbol": "🦨", "unicode": "U+1F9A8"},
        {"name": "Sloth", "symbol": "🦥", "unicode": "U+1F9A5"},
        {"name": "Anteater", "symbol": "🐜", "unicode": "U+1F41C"},
        {"name": "Hippopotamus", "symbol": "🦛", "unicode": "U+1F99B"},
        {"name": "Rhinoceros", "symbol": "🦏", "unicode": "U+1F98F"},
        {"name": "Monkey Face", "symbol": "🐵", "unicode": "U+1F435"},
        {"name": "Monkey", "symbol": "🐒", "unicode": "U+1F412"},
        {"name": "Chicken", "symbol": "🐔", "unicode": "U+1F414"},
        {"name": "Chick", "symbol": "🐤", "unicode": "U+1F424"},
        {"name": "Hatching Chick", "symbol": "🐣", "unicode": "U+1F423"},
        {"name": "Rooster", "symbol": "🐓", "unicode": "U+1F413"},
        {"name": "Turkey", "symbol": "🦃", "unicode": "U+1F983"},
        {"name": "Dove", "symbol": "🕊️", "unicode": "U+1F54A"},
        {"name": "Penguin", "symbol": "🐧", "unicode": "U+1F427"},
        {"name": "Ostrich", "symbol": "🐦", "unicode": "U+1F426"},
    ],
    
    "Food & Drinks": [
        {"name": "Red Apple", "symbol": "🍎", "unicode": "U+1F34E"},
        {"name": "Green Apple", "symbol": "🍏", "unicode": "U+1F34F"},
        {"name": "Pear", "symbol": "🍐", "unicode": "U+1F350"},
        {"name": "Tangerine", "symbol": "🍊", "unicode": "U+1F34A"},
        {"name": "Lemon", "symbol": "🍋", "unicode": "U+1F34B"},
        {"name": "Banana", "symbol": "🍌", "unicode": "U+1F34C"},
        {"name": "Watermelon", "symbol": "🍉", "unicode": "U+1F349"},
        {"name": "Grapes", "symbol": "🍇", "unicode": "U+1F347"},
        {"name": "Strawberry", "symbol": "🍓", "unicode": "U+1F353"},
        {"name": "Melon", "symbol": "🍈", "unicode": "U+1F348"},
        {"name": "Cherries", "symbol": "🍒", "unicode": "U+1F352"},
        {"name": "Peach", "symbol": "🍑", "unicode": "U+1F351"},
        {"name": "Pineapple", "symbol": "🍍", "unicode": "U+1F34D"},
        {"name": "Kiwi Fruit", "symbol": "🥝", "unicode": "U+1F95D"},
        {"name": "Tomato", "symbol": "🍅", "unicode": "U+1F345"},
        {"name": "Eggplant", "symbol": "🍆", "unicode": "U+1F346"},
        {"name": "Avocado", "symbol": "🥑", "unicode": "U+1F951"},
        {"name": "Potato", "symbol": "🥔", "unicode": "U+1F954"},
        {"name": "Carrot", "symbol": "🥕", "unicode": "U+1F955"},
        {"name": "Hot Pepper", "symbol": "🌶️", "unicode": "U+1F336"},
        {"name": "Cucumber", "symbol": "🥒", "unicode": "U+1F952"},
        {"name": "Leafy Green", "symbol": "🥬", "unicode": "U+1F96C"},
        {"name": "Broccoli", "symbol": "🥦", "unicode": "U+1F966"},
        {"name": "Garlic", "symbol": "🧄", "unicode": "U+1F9C4"},
        {"name": "Onion", "symbol": "🧅", "unicode": "U+1F9C5"},
        {"name": "Mushroom", "symbol": "🍄", "unicode": "U+1F344"},
        {"name": "Peanuts", "symbol": "🥜", "unicode": "U+1F95C"},
        {"name": "Chestnut", "symbol": "🌰", "unicode": "U+1F330"},
        {"name": "Bread", "symbol": "🍞", "unicode": "U+1F35E"},
        {"name": "Croissant", "symbol": "🥐", "unicode": "U+1F950"},
        {"name": "Baguette Bread", "symbol": "🥖", "unicode": "U+1F956"},
        {"name": "Pretzel", "symbol": "🥨", "unicode": "U+1F968"},
        {"name": "Cheese Wedge", "symbol": "🧀", "unicode": "U+1F9C0"},
        {"name": "Egg", "symbol": "🥚", "unicode": "U+1F95A"},
        {"name": "Cooking", "symbol": "🍳", "unicode": "U+1F373"},
        {"name": "Bacon", "symbol": "🥓", "unicode": "U+1F953"},
        {"name": "Cut of Meat", "symbol": "🥩", "unicode": "U+1F969"},
        {"name": "Poultry Leg", "symbol": "🍗", "unicode": "U+1F357"},
        {"name": "Meat on Bone", "symbol": "🍖", "unicode": "U+1F356"},
        {"name": "Hot Dog", "symbol": "🌭", "unicode": "U+1F32D"},
        {"name": "Hamburger", "symbol": "🍔", "unicode": "U+1F354"},
        {"name": "Fries", "symbol": "🍟", "unicode": "U+1F32F"},
        {"name": "Pizza", "symbol": "🍕", "unicode": "U+1F355"},
        {"name": "Taco", "symbol": "🌮", "unicode": "U+1F32E"},
        {"name": "Burrito", "symbol": "🌯", "unicode": "U+1F32F"},
        {"name": "Tamale", "symbol": "🫔", "unicode": "U+1FAF4"},
        {"name": "Stuffed Flatbread", "symbol": "🥙", "unicode": "U+1F959"},
        {"name": "Falafel", "symbol": "🧆", "unicode": "U+1F9C6"},
        {"name": "Cooked Rice", "symbol": "🍚", "unicode": "U+1F35A"},
        {"name": "Rice Ball", "symbol": "🍙", "unicode": "U+1F359"},
        {"name": "Rice Cracker", "symbol": "🍘", "unicode": "U+1F358"},
        {"name": "Fish Cake with Swirl", "symbol": "🍥", "unicode": "U+1F365"},
        {"name": "Fortune Cookie", "symbol": "🥠", "unicode": "U+1F960"},
        {"name": "Moon Cake", "symbol": "🥮", "unicode": "U+1F96E"},
        {"name": "Oden", "symbol": "🍢", "unicode": "U+1F362"},
        {"name": "Dango", "symbol": "🍡", "unicode": "U+1F361"},
        {"name": "Shaved Ice", "symbol": "🍧", "unicode": "U+1F367"},
        {"name": "Ice Cream", "symbol": "🍨", "unicode": "U+1F368"},
        {"name": "Doughnut", "symbol": "🍩", "unicode": "U+1F369"},
        {"name": "Cookie", "symbol": "🍪", "unicode": "U+1F36A"},
        {"name": "Birthday Cake", "symbol": "🎂", "unicode": "U+1F382"},
        {"name": "Shortcake", "symbol": "🍰", "unicode": "U+1F370"},
        {"name": "Chocolate Bar", "symbol": "🍫", "unicode": "U+1F36B"},
        {"name": "Candy", "symbol": "🍬", "unicode": "U+1F36C"},
        {"name": "Lollipop", "symbol": "🍭", "unicode": "U+1F36D"},
        {"name": "Custard", "symbol": "🍮", "unicode": "U+1F36E"},
        {"name": "Honey Pot", "symbol": "🍯", "unicode": "U+1F36F"},
        {"name": "Baby Bottle", "symbol": "🍼", "unicode": "U+1F37C"},
        {"name": "Glass of Milk", "symbol": "🥛", "unicode": "U+1F95B"},
        {"name": "Hot Beverage", "symbol": "☕", "unicode": "U+2615"},
        {"name": "Teacup Without Handle", "symbol": "🍵", "unicode": "U+1F375"},
        {"name": "Sake", "symbol": "🍶", "unicode": "U+1F376"},
        {"name": "Bottle with Popping Cork", "symbol": "🍾", "unicode": "U+1F37E"},
        {"name": "Wine Glass", "symbol": "🍷", "unicode": "U+1F377"},
        {"name": "Cocktail Glass", "symbol": "🍸", "unicode": "U+1F378"},
        {"name": "Tropical Drink", "symbol": "🍹", "unicode": "U+1F379"},
        {"name": "Beer Mug", "symbol": "🍺", "unicode": "U+1F37A"},
        {"name": "Clinking Beer Mugs", "symbol": "🍻", "unicode": "U+1F37B"},
        {"name": "Clinking Glasses", "symbol": "🥂", "unicode": "U+1F942"},
        {"name": "Tumbler Glass", "symbol": "🥃", "unicode": "U+1F943"},
        {"name": "Cup with Straw", "symbol": "🥤", "unicode": "U+1F964"},
        {"name": "Bubble Tea", "symbol": "🧋", "unicode": "U+1F9CB"},
        {"name": "Beverage Box", "symbol": "🧃", "unicode": "U+1F9C3"},
        {"name": "Mate", "symbol": "🧉", "unicode": "U+1F9C9"},
        {"name": "Ice", "symbol": "🧊", "unicode": "U+1F9CA"},
        {"name": "Salt", "symbol": "🧂", "unicode": "U+1F9C2"},
    ],
    
    "Activity": [
        {"name": "American Football", "symbol": "🏈", "unicode": "U+1F3C8"},
        {"name": "Basketball", "symbol": "🏀", "unicode": "U+1F3C0"},
        {"name": "Soccer Ball", "symbol": "⚽", "unicode": "U+26BD"},
        {"name": "Baseball", "symbol": "⚾", "unicode": "U+26BE"},
        {"name": "Tennis", "symbol": "🎾", "unicode": "U+1F3BE"},
        {"name": "Volleyball", "symbol": "🏐", "unicode": "U+1F3D0"},
        {"name": "Table Tennis", "symbol": "🏓", "unicode": "U+1F3D3"},
        {"name": "Pool 8 Ball", "symbol": "🎱", "unicode": "U+1F3B1"},
        {"name": "Golf", "symbol": "⛳", "unicode": "U+26F3"},
        {"name": "Bowling", "symbol": "🎳", "unicode": "U+1F3B3"},
        {"name": "Cricket", "symbol": "🏏", "unicode": "U+1F3CF"},
        {"name": "Field Hockey", "symbol": "🏑", "unicode": "U+1F3D1"},
        {"name": "Ice Hockey", "symbol": "🏒", "unicode": "U+1F3D2"},
        {"name": "Badminton", "symbol": "🏸", "unicode": "U+1F3F8"},
        {"name": "Boxing Glove", "symbol": "🥊", "unicode": "U+1F94A"},
        {"name": "Martial Arts Uniform", "symbol": "🥋", "unicode": "U+1F94B"},
        {"name": "Goal Net", "symbol": "🥅", "unicode": "U+1F945"},
        {"name": "Ice Skate", "symbol": "⛸️", "unicode": "U+26F8"},
        {"name": "Skier", "symbol": "⛷️", "unicode": "U+26F7"},
        {"name": "Snowboarder", "symbol": "🏂", "unicode": "U+1F3C2"},
        {"name": "Person Lifting Weights", "symbol": "🏋️", "unicode": "U+1F3CB"},
        {"name": "Person in Lotus Position", "symbol": "🧘", "unicode": "U+1F9D8"},
        {"name": "Swimmer", "symbol": "🏊", "unicode": "U+1F3CA"},
        {"name": "Person Bouncing Ball", "symbol": "⛹️", "unicode": "U+26F9"},
        {"name": "Runner", "symbol": "🏃", "unicode": "U+1F3C3"},
        {"name": "Horse Racing", "symbol": "🏇", "unicode": "U+1F3C7"},
        {"name": "Bicycle", "symbol": "🚴", "unicode": "U+1F6B4"},
        {"name": "Motorcycle", "symbol": "🏍️", "unicode": "U+1F3CD"},
        {"name": "Mountain Biking", "symbol": "🚵", "unicode": "U+1F6B5"},
        {"name": "Rowing Boat", "symbol": "🚣", "unicode": "U+1F6A3"},
        {"name": "Surfer", "symbol": "🏄", "unicode": "U+1F3C4"},
        {"name": "Skateboarding", "symbol": "🛹", "unicode": "U+1F6F9"},
        {"name": "Bow and Arrow", "symbol": "🏹", "unicode": "U+1F3F9"},
        {"name": "Roller Skate", "symbol": "🛼", "unicode": "U+1F6FC"},
        {"name": "Kayaking", "symbol": "🛶", "unicode": "U+1F6F6"},
        {"name": "Scuba Diving", "symbol": "🤿", "unicode": "U+1F93F"},
        {"name": "Fishing", "symbol": "🎣", "unicode": "U+1F3A3"},
        {"name": "Walking", "symbol": "🚶", "unicode": "U+1F6B6"},
        {"name": "Videogame", "symbol": "🎮", "unicode": "U+1F3AE"},
        {"name": "Dice", "symbol": "🎲", "unicode": "U+1F3B2"},
        {"name": "Chess Pawn", "symbol": "♟️", "unicode": "U+265F"},
        {"name": "Circus Tent", "symbol": "🎪", "unicode": "U+1F3AA"},
        {"name": "Bullseye", "symbol": "🎯", "unicode": "U+1F3AF"},
    ],
    
    "Travel & Places": [
        {"name": "Globe Showing Europe-Africa", "symbol": "🌍", "unicode": "U+1F30D"},
        {"name": "Globe Showing Americas", "symbol": "🌎", "unicode": "U+1F30E"},
        {"name": "Globe Showing Asia-Australia", "symbol": "🌏", "unicode": "U+1F30F"},
        {"name": "Globe with Meridians", "symbol": "🌐", "unicode": "U+1F310"},
        {"name": "World Map", "symbol": "🗺️", "unicode": "U+1F5FA"},
        {"name": "Japan", "symbol": "🗾", "unicode": "U+1F5FE"},
        {"name": "Compass", "symbol": "🧭", "unicode": "U+1F9ED"},
        {"name": "Mountain", "symbol": "⛰️", "unicode": "U+26F0"},
        {"name": "Volcano", "symbol": "🌋", "unicode": "U+1F30B"},
        {"name": "Mount Fuji", "symbol": "🗻", "unicode": "U+1F5FB"},
        {"name": "Camping", "symbol": "🏕️", "unicode": "U+1F3D5"},
        {"name": "Beach with Umbrella", "symbol": "🏖️", "unicode": "U+1F3D6"},
        {"name": "Desert", "symbol": "🏜️", "unicode": "U+1F3DC"},
        {"name": "Desert Island", "symbol": "🏝️", "unicode": "U+1F3DD"},
        {"name": "National Park", "symbol": "🏞️", "unicode": "U+1F3DE"},
        {"name": "Stadium", "symbol": "🏟️", "unicode": "U+1F3DF"},
        {"name": "Classical Building", "symbol": "🏛️", "unicode": "U+1F3DB"},
        {"name": "Building", "symbol": "🏢", "unicode": "U+1F3E2"},
        {"name": "Cityscape", "symbol": "🏙️", "unicode": "U+1F3D9"},
        {"name": "Derelict House", "symbol": "🏚️", "unicode": "U+1F3DA"},
        {"name": "House", "symbol": "🏠", "unicode": "U+1F3E0"},
        {"name": "House with Garden", "symbol": "🏡", "unicode": "U+1F3E1"},
        {"name": "Office Building", "symbol": "🏬", "unicode": "U+1F3E2"},
        {"name": "Japanese Post Office", "symbol": "🏣", "unicode": "U+1F3E3"},
        {"name": "Post Office", "symbol": "🏤", "unicode": "U+1F3E4"},
        {"name": "Hospital", "symbol": "🏥", "unicode": "U+1F3E5"},
        {"name": "Bank", "symbol": "🏦", "unicode": "U+1F3E6"},
        {"name": "Hotel", "symbol": "🏨", "unicode": "U+1F3E8"},
        {"name": "Love Hotel", "symbol": "🏩", "unicode": "U+1F3E9"},
        {"name": "Convenience Store", "symbol": "🏪", "unicode": "U+1F3EA"},
        {"name": "School", "symbol": "🏫", "unicode": "U+1F3EB"},
        {"name": "Factory", "symbol": "🏭", "unicode": "U+1F3ED"},
        {"name": "Japanese Castle", "symbol": "🏯", "unicode": "U+1F3EF"},
        {"name": "European Castle", "symbol": "🏰", "unicode": "U+1F3F0"},
        {"name": "Wedding", "symbol": "💒", "unicode": "U+1F492"},
        {"name": "Tokyo Tower", "symbol": "🗼", "unicode": "U+1F5FC"},
        {"name": "Statue of Liberty", "symbol": "🗽", "unicode": "U+1F5FD"},
        {"name": "Airplane", "symbol": "✈️", "unicode": "U+2708"},
        {"name": "Airplane Departure", "symbol": "🛫", "unicode": "U+1F6EB"},
        {"name": "Airplane Arrival", "symbol": "🛬", "unicode": "U+1F6EC"},
        {"name": "Helicopter", "symbol": "🚁", "unicode": "U+1F681"},
        {"name": "Steam Locomotive", "symbol": "🚂", "unicode": "U+1F682"},
        {"name": "Train", "symbol": "🚆", "unicode": "U+1F686"},
        {"name": "Train Car", "symbol": "🚊", "unicode": "U+1F68A"},
        {"name": "Bullet Train", "symbol": "🚅", "unicode": "U+1F685"},
        {"name": "Mountain Railway", "symbol": "🚞", "unicode": "U+1F69E"},
        {"name": "Monorail", "symbol": "🚝", "unicode": "U+1F69D"},
        {"name": "Tram Car", "symbol": "🚋", "unicode": "U+1F68B"},
        {"name": "Bus", "symbol": "🚌", "unicode": "U+1F68C"},
        {"name": "Oncoming Bus", "symbol": "🚍", "unicode": "U+1F68D"},
        {"name": "Trolleybus", "symbol": "🚎", "unicode": "U+1F68E"},
        {"name": "Minibus", "symbol": "🚐", "unicode": "U+1F690"},
        {"name": "Ambulance", "symbol": "🚑", "unicode": "U+1F691"},
        {"name": "Fire Engine", "symbol": "🚒", "unicode": "U+1F692"},
        {"name": "Police Car", "symbol": "🚓", "unicode": "U+1F693"},
        {"name": "Oncoming Police Car", "symbol": "🚔", "unicode": "U+1F694"},
        {"name": "Taxi", "symbol": "🚕", "unicode": "U+1F695"},
        {"name": "Oncoming Taxi", "symbol": "🚖", "unicode": "U+1F696"},
        {"name": "Car", "symbol": "🚗", "unicode": "U+1F697"},
        {"name": "Oncoming Car", "symbol": "🚘", "unicode": "U+1F698"},
        {"name": "Blue Car", "symbol": "🚙", "unicode": "U+1F699"},
        {"name": "Truck", "symbol": "🚚", "unicode": "U+1F69A"},
        {"name": "Articulated Lorry", "symbol": "🚛", "unicode": "U+1F69B"},
        {"name": "Tractor", "symbol": "🚜", "unicode": "U+1F69C"},
        {"name": "Racing Car", "symbol": "🏎️", "unicode": "U+1F3CE"},
        {"name": "Motor Scooter", "symbol": "🛵", "unicode": "U+1F6B5"},
        {"name": "Manual Wheelchair", "symbol": "🦽", "unicode": "U+1F9FD"},
        {"name": "Motorized Wheelchair", "symbol": "🦼", "unicode": "U+1F9FC"},
        {"name": "Bike", "symbol": "🛲", "unicode": "U+1F6FA"},
        {"name": "Kickboard", "symbol": "🛴", "unicode": "U+1F6F4"},
        {"name": "Rocket", "symbol": "🚀", "unicode": "U+1F680"},
        {"name": "Satellite", "symbol": "🛰️", "unicode": "U+1F6F0"},
        {"name": "Ship", "symbol": "🚢", "unicode": "U+1F6A2"},
        {"name": "Anchor", "symbol": "⚓", "unicode": "U+2693"},
        {"name": "Sailboat", "symbol": "⛵", "unicode": "U+26F5"},
        {"name": "Speedboat", "symbol": "🛥️", "unicode": "U+1F6E5"},
        {"name": "Motor Boat", "symbol": "🛳️", "unicode": "U+1F6F3"},
        {"name": "Ferris Wheel", "symbol": "🎡", "unicode": "U+1F3A1"},
        {"name": "Roller Coaster", "symbol": "🎢", "unicode": "U+1F3A2"},
        {"name": "Carousel", "symbol": "🎠", "unicode": "U+1F3A0"},
        {"name": "Sunrise", "symbol": "🌅", "unicode": "U+1F305"},
        {"name": "Sunset", "symbol": "🌆", "unicode": "U+1F306"},
        {"name": "Bridge at Night", "symbol": "🌉", "unicode": "U+1F309"},
        {"name": "Lightning Cloud", "symbol": "⛈️", "unicode": "U+26C8"},
        {"name": "Sunny", "symbol": "☀️", "unicode": "U+2600"},
        {"name": "Cloud", "symbol": "☁️", "unicode": "U+2601"},
        {"name": "Rainbow", "symbol": "🌈", "unicode": "U+1F308"},
        {"name": "Moon", "symbol": "🌙", "unicode": "U+1F319"},
        {"name": "Tent", "symbol": "⛺", "unicode": "U+26FA"},
        {"name": "Umbrella on Ground", "symbol": "⛱️", "unicode": "U+26F1"},
    ],
    
    "Objects": [
        {"name": "Watch", "symbol": "⌚", "unicode": "U+231A"},
        {"name": "Mobile Phone", "symbol": "📱", "unicode": "U+1F4F1"},
        {"name": "Laptop", "symbol": "💻", "unicode": "U+1F4BB"},
        {"name": "Desktop Computer", "symbol": "🖥️", "unicode": "U+1F5A5"},
        {"name": "Printer", "symbol": "🖨️", "unicode": "U+1F5A8"},
        {"name": "Computer Mouse", "symbol": "🖱️", "unicode": "U+1F5B1"},
        {"name": "Trackball", "symbol": "🖲️", "unicode": "U+1F5B2"},
        {"name": "Keyboard", "symbol": "⌨️", "unicode": "U+2328"},
        {"name": "Pencil", "symbol": "✏️", "unicode": "U+270F"},
        {"name": "Pen", "symbol": "🖊️", "unicode": "U+1F5A2"},
        {"name": "Crayon", "symbol": "🖍️", "unicode": "U+1F5D1"},
        {"name": "Book", "symbol": "📖", "unicode": "U+1F4D6"},
        {"name": "Notebook", "symbol": "📓", "unicode": "U+1F4D3"},
        {"name": "Ledger", "symbol": "📒", "unicode": "U+1F4D2"},
        {"name": "Page with Curl", "symbol": "📃", "unicode": "U+1F4C3"},
        {"name": "Scroll", "symbol": "📜", "unicode": "U+1F4DC"},
        {"name": "Page Facing Up", "symbol": "📄", "unicode": "U+1F4C4"},
        {"name": "Newspaper", "symbol": "📰", "unicode": "U+1F4F0"},
        {"name": "Bookmark Tabs", "symbol": "📑", "unicode": "U+1F4D1"},
        {"name": "Bookmark", "symbol": "🔖", "unicode": "U+1F516"},
        {"name": "Money Bag", "symbol": "💰", "unicode": "U+1F4B0"},
        {"name": "Coin", "symbol": "🪙", "unicode": "U+1FA99"},
        {"name": "Yen Banknote", "symbol": "💴", "unicode": "U+1F4B4"},
        {"name": "Dollar Banknote", "symbol": "💵", "unicode": "U+1F4B5"},
        {"name": "Euro Banknote", "symbol": "💶", "unicode": "U+1F4B6"},
        {"name": "Pound Banknote", "symbol": "💷", "unicode": "U+1F4B7"},
        {"name": "Money with Wings", "symbol": "💸", "unicode": "U+1F4B8"},
        {"name": "Credit Card", "symbol": "💳", "unicode": "U+1F4B3"},
        {"name": "Receipt", "symbol": "🧾", "unicode": "U+1F9FE"},
        {"name": "Scissors", "symbol": "✂️", "unicode": "U+2702"},
        {"name": "Fountain Pen", "symbol": "🖋️", "unicode": "U+1F5CF"},
        {"name": "Paintbrush", "symbol": "🖌️", "unicode": "U+1F5CC"},
        {"name": "Envelopes", "symbol": "📬", "unicode": "U+1F4EC"},
        {"name": "Package", "symbol": "📦", "unicode": "U+1F4E6"},
        {"name": "Briefcase", "symbol": "💼", "unicode": "U+1F4BC"},
        {"name": "Magnet", "symbol": "🧲", "unicode": "U+1F9F2"},
        {"name": "Toolbox", "symbol": "🧰", "unicode": "U+1F9F0"},
        {"name": "Hammer", "symbol": "🔨", "unicode": "U+1F528"},
        {"name": "Wrench", "symbol": "🔧", "unicode": "U+1F527"},
        {"name": "Screwdriver", "symbol": "🪛", "unicode": "U+1FAB1"},
        {"name": "Saw", "symbol": "🪚", "unicode": "U+1FAAA"},
        {"name": "Axe", "symbol": "🪓", "unicode": "U+1FAAB"},
        {"name": "Pickaxe", "symbol": "⛏️", "unicode": "U+26CF"},
        {"name": "Hammer and Pick", "symbol": "⚒️", "unicode": "U+2692"},
        {"name": "Hammer and Wrench", "symbol": "🛠️", "unicode": "U+1F6E0"},
        {"name": "Gear", "symbol": "⚙️", "unicode": "U+2699"},
        {"name": "Clamp", "symbol": "🗜️", "unicode": "U+1F5DC"},
        {"name": "Ladder", "symbol": "🪜", "unicode": "U+1FAA3"},
        {"name": "Bucket", "symbol": "🪣", "unicode": "U+1FAAB"},
        {"name": "Rope", "symbol": "🪢", "unicode": "U+1FAAE"},
        {"name": "Lotion Bottle", "symbol": "🧴", "unicode": "U+1F9F4"},
        {"name": "Soap", "symbol": "🧼", "unicode": "U+1F9FC"},
        {"name": "Plug", "symbol": "🔌", "unicode": "U+1F50C"},
        {"name": "Microscope", "symbol": "🔬", "unicode": "U+1F52C"},
        {"name": "Telescope", "symbol": "🔭", "unicode": "U+1F52D"},
        {"name": "Syringe", "symbol": "💉", "unicode": "U+1F489"},
        {"name": "Toothbrush", "symbol": "🪥", "unicode": "U+1FAAA"},
        {"name": "Toilet Paper", "symbol": "🧻", "unicode": "U+1F9FB"},
        {"name": "Basket", "symbol": "🧺", "unicode": "U+1F9FA"},
        {"name": "Bathtub", "symbol": "🛁", "unicode": "U+1F6C1"},
    ],
    
    "Symbols": [
        {"name": "Revolving Hearts", "symbol": "�", "unicode": "U+1F49E"},
        {"name": "Peace Symbol", "symbol": "☮️", "unicode": "U+262E"},
        {"name": "Latin Cross", "symbol": "✝️", "unicode": "U+271D"},
        {"name": "Star of David", "symbol": "✡️", "unicode": "U+2721"},
        {"name": "Wheel of Dharma", "symbol": "☸️", "unicode": "U+2638"},
        {"name": "Star and Crescent", "symbol": "☪️", "unicode": "U+262A"},
        {"name": "Om", "symbol": "🕉️", "unicode": "U+1F549"},
        {"name": "Yin Yang", "symbol": "☯️", "unicode": "U+262F"},
        {"name": "Orthodox Cross", "symbol": "☦️", "unicode": "U+2626"},
        {"name": "Menorah", "symbol": "🕎", "unicode": "U+1F54E"},
        {"name": "Dotted Six-Pointed Star", "symbol": "🔯", "unicode": "U+1F52F"},
        {"name": "Aries", "symbol": "♈", "unicode": "U+2648"},
        {"name": "Taurus", "symbol": "♉", "unicode": "U+2649"},
        {"name": "Gemini", "symbol": "♊", "unicode": "U+264A"},
        {"name": "Cancer", "symbol": "♋", "unicode": "U+264B"},
        {"name": "Leo", "symbol": "♌", "unicode": "U+264C"},
        {"name": "Virgo", "symbol": "♍", "unicode": "U+264D"},
        {"name": "Libra", "symbol": "♎", "unicode": "U+264E"},
        {"name": "Scorpio", "symbol": "♏", "unicode": "U+264F"},
        {"name": "Sagittarius", "symbol": "♐", "unicode": "U+2650"},
        {"name": "Capricorn", "symbol": "♑", "unicode": "U+2651"},
        {"name": "Aquarius", "symbol": "♒", "unicode": "U+2652"},
        {"name": "Pisces", "symbol": "♓", "unicode": "U+2653"},
        {"name": "Exclamation Mark", "symbol": "❗", "unicode": "U+2757"},
        {"name": "Double Exclamation Mark", "symbol": "‼️", "unicode": "U+203C"},
        {"name": "Question Mark", "symbol": "❓", "unicode": "U+2753"},
        {"name": "Double Question Mark", "symbol": "❔", "unicode": "U+2754"},
        {"name": "Exclamation Question Mark", "symbol": "⁉️", "unicode": "U+2049"},
        {"name": "Prohibited", "symbol": "🚫", "unicode": "U+1F6AB"},
        {"name": "No Entry", "symbol": "⛔", "unicode": "U+26D4"},
        {"name": "Radioactive", "symbol": "☢️", "unicode": "U+2622"},
        {"name": "Biohazard", "symbol": "☣️", "unicode": "U+2623"},
        {"name": "High Voltage", "symbol": "⚡", "unicode": "U+26A1"},
        {"name": "Snowflake", "symbol": "❄️", "unicode": "U+2744"},
        {"name": "Dizzy", "symbol": "💫", "unicode": "U+1F4AB"},
        {"name": "Dash", "symbol": "💨", "unicode": "U+1F4A8"},
        {"name": "Comic Boom", "symbol": "💥", "unicode": "U+1F4A5"},
        {"name": "Fire", "symbol": "🔥", "unicode": "U+1F525"},
        {"name": "Droplet", "symbol": "💧", "unicode": "U+1F4A7"},
        {"name": "Ocean Wave", "symbol": "🌊", "unicode": "U+1F30A"},
        {"name": "Bell", "symbol": "🔔", "unicode": "U+1F514"},
        {"name": "Bell with Slash", "symbol": "🔕", "unicode": "U+1F515"},
        {"name": "Loudspeaker", "symbol": "📢", "unicode": "U+1F4A2"},
        {"name": "Megaphone", "symbol": "📣", "unicode": "U+1F4A3"},
        {"name": "Outbox Tray", "symbol": "📤", "unicode": "U+1F4E4"},
        {"name": "Inbox Tray", "symbol": "📥", "unicode": "U+1F4E5"},
        {"name": "Label", "symbol": "🏷️", "unicode": "U+1F3F7"},
        {"name": "Mailbox Closed", "symbol": "📪", "unicode": "U+1F4EA"},
        {"name": "Mailbox Open", "symbol": "📫", "unicode": "U+1F4EB"},
        {"name": "Mailbox with No Mail", "symbol": "📭", "unicode": "U+1F4ED"},
        {"name": "Postbox", "symbol": "📮", "unicode": "U+1F4EE"},
        {"name": "Postal Horn", "symbol": "📯", "unicode": "U+1F4AF"},
        {"name": "Pushpin", "symbol": "📍", "unicode": "U+1F4CD"},
        {"name": "Triangular Flag", "symbol": "🚩", "unicode": "U+1F6A9"},
        {"name": "Ribbon", "symbol": "🎀", "unicode": "U+1F380"},
        {"name": "Gift", "symbol": "🎁", "unicode": "U+1F381"},
        {"name": "Reminder Ribbon", "symbol": "🎗️", "unicode": "U+1F397"},
        {"name": "Admission Tickets", "symbol": "🎫", "unicode": "U+1F3AB"},
        {"name": "Performing Arts", "symbol": "🎭", "unicode": "U+1F3AD"},
        {"name": "Clapper Board", "symbol": "🎬", "unicode": "U+1F3AC"},
        {"name": "Movie Camera", "symbol": "🎥", "unicode": "U+1F3A5"},
        {"name": "Camera", "symbol": "📷", "unicode": "U+1F4F7"},
        {"name": "Camera with Flash", "symbol": "📸", "unicode": "U+1F4F8"},
        {"name": "Telephone Receiver", "symbol": "📞", "unicode": "U+1F4DE"},
        {"name": "Telephone", "symbol": "☎️", "unicode": "U+260E"},
        {"name": "Fax Machine", "symbol": "📠", "unicode": "U+1F4E0"},
        {"name": "Television", "symbol": "📺", "unicode": "U+1F4FA"},
        {"name": "Radio", "symbol": "📻", "unicode": "U+1F4FB"},
        {"name": "Pager", "symbol": "📟", "unicode": "U+1F4DF"},
        {"name": "Stopwatch", "symbol": "⏱️", "unicode": "U+23F1"},
        {"name": "Timer Clock", "symbol": "⏲️", "unicode": "U+23F2"},
        {"name": "Alarm Clock", "symbol": "⏰", "unicode": "U+23F0"},
        {"name": "Clock", "symbol": "🕐", "unicode": "U+1F550"},
        {"name": "Hourglass Done", "symbol": "⌛", "unicode": "U+231B"},
        {"name": "Hourglass", "symbol": "⏳", "unicode": "U+23F3"},
        {"name": "Satellite Antenna", "symbol": "📡", "unicode": "U+1F4E1"},
        {"name": "Battery", "symbol": "🔋", "unicode": "U+1F50B"},
        {"name": "Flashlight", "symbol": "🔦", "unicode": "U+1F526"},
        {"name": "Candle", "symbol": "🕯️", "unicode": "U+1F56F"},
        {"name": "Wastebasket", "symbol": "🗑️", "unicode": "U+1F5D1"},
        {"name": "Oil Drum", "symbol": "🛢️", "unicode": "U+1F6E2"},
        {"name": "Bomb", "symbol": "💣", "unicode": "U+1F4A3"},
        {"name": "Knife", "symbol": "🔪", "unicode": "U+1F52A"},
        {"name": "Gun", "symbol": "🔫", "unicode": "U+1F52B"},
        {"name": "Pill", "symbol": "💊", "unicode": "U+1F48A"},
        {"name": "Toilet", "symbol": "🚽", "unicode": "U+1F6BD"},
        {"name": "Coffin", "symbol": "⚰️", "unicode": "U+26B0"},
        {"name": "Funeral Urn", "symbol": "⚱️", "unicode": "U+26B1"},
        {"name": "Amphora", "symbol": "🏺", "unicode": "U+1F3FA"},
        # Additional symbols to reach 800+ emojis
        {"name": "Currency Exchange", "symbol": "💱", "unicode": "U+1F4B1"},
        {"name": "Heavy Dollar Sign", "symbol": "💲", "unicode": "U+1F4B2"},
        {"name": "Gem Stone", "symbol": "💎", "unicode": "U+1F48E"},
        {"name": "Chopsticks", "symbol": "🥢", "unicode": "U+1F962"},
        {"name": "Flatbread", "symbol": "🫓", "unicode": "U+1FAD3"},
        {"name": "Butter", "symbol": "🧈", "unicode": "U+1F9C8"},
        {"name": "Pouring Liquid", "symbol": "🫗", "unicode": "U+1FAD7"},
        {"name": "Jar", "symbol": "🫙", "unicode": "U+1FAD9"},
        {"name": "Hollow Red Circle", "symbol": "⭕", "unicode": "U+2B55"},
        {"name": "Orange Circle", "symbol": "🟠", "unicode": "U+1F7E0"},
        {"name": "Yellow Circle", "symbol": "🟡", "unicode": "U+1F7E1"},
        {"name": "Green Circle", "symbol": "🟢", "unicode": "U+1F7E2"},
        {"name": "Blue Circle", "symbol": "🔵", "unicode": "U+1F535"},
        {"name": "Purple Circle", "symbol": "🟣", "unicode": "U+1F7E3"},
        {"name": "Brown Circle", "symbol": "🟤", "unicode": "U+1F7E4"},
        {"name": "Black Circle", "symbol": "⚫", "unicode": "U+26AB"},
        {"name": "White Circle", "symbol": "⚪", "unicode": "U+26AA"},
        {"name": "Red Square", "symbol": "🟥", "unicode": "U+1F7E5"},
        {"name": "Orange Square", "symbol": "🟧", "unicode": "U+1F7E7"},
        {"name": "Yellow Square", "symbol": "🟨", "unicode": "U+1F7E8"},
        {"name": "Green Square", "symbol": "🟩", "unicode": "U+1F7E9"},
        {"name": "Blue Square", "symbol": "🟦", "unicode": "U+1F7E6"},
        {"name": "Purple Square", "symbol": "🟪", "unicode": "U+1F7EA"},
        {"name": "Brown Square", "symbol": "🟫", "unicode": "U+1F7EB"},
        {"name": "Black Square", "symbol": "⬛", "unicode": "U+2B1B"},
        {"name": "White Square", "symbol": "⬜", "unicode": "U+2B1C"},
        {"name": "Waving Hand", "symbol": "👋", "unicode": "U+1F44B"},
        {"name": "Waving Hand Light Skin", "symbol": "👋🏻", "unicode": "U+1F44B"},
        {"name": "Waving Hand Medium Light Skin", "symbol": "👋🏼", "unicode": "U+1F44B"},
        {"name": "Waving Hand Medium Skin", "symbol": "👋🏽", "unicode": "U+1F44B"},
        {"name": "Waving Hand Medium Dark Skin", "symbol": "👋🏾", "unicode": "U+1F44B"},
        {"name": "Waving Hand Dark Skin", "symbol": "👋🏿", "unicode": "U+1F44B"},
        {"name": "Family", "symbol": "👨‍👩‍👧‍👦", "unicode": "U+1F468"},
        {"name": "Rainbow Flag", "symbol": "🏳️‍🌈", "unicode": "U+1F3F3"},
        {"name": "United States", "symbol": "🇺🇸", "unicode": "U+1F1FA"},
        {"name": "Person Standing", "symbol": "🧍", "unicode": "U+1F9CD"},
        {"name": "Person Kneeling", "symbol": "🧎", "unicode": "U+1F9CE"},
        {"name": "Person in Motorized Wheelchair", "symbol": "🧑‍🦼", "unicode": "U+1F9D1"},
        {"name": "Person in Manual Wheelchair", "symbol": "🧑‍🦽", "unicode": "U+1F9D1"},
        {"name": "Person in Tuxedo", "symbol": "🤵", "unicode": "U+1F935"},
        {"name": "Person with Veil", "symbol": "👰", "unicode": "U+1F470"},
        {"name": "Pregnant Woman", "symbol": "🤰", "unicode": "U+1F930"},
        {"name": "Breast-Feeding", "symbol": "🤱", "unicode": "U+1F931"},
        {"name": "Person Crown", "symbol": "🫅", "unicode": "U+1FA85"},
        {"name": "Mx Claus", "symbol": "🧑‍🎄", "unicode": "U+1F9D1"},
        {"name": "Mrs Claus", "symbol": "🤶", "unicode": "U+1F936"},
        {"name": "Superhero", "symbol": "🦸", "unicode": "U+1F9B8"},
        {"name": "Supervillain", "symbol": "🦹", "unicode": "U+1F9B9"},
        {"name": "Mage", "symbol": "🧙", "unicode": "U+1F9D9"},
        {"name": "Fairy", "symbol": "🧚", "unicode": "U+1F9DA"},
        {"name": "Vampire", "symbol": "🧛", "unicode": "U+1F9DB"},
        {"name": "Merperson", "symbol": "🧜", "unicode": "U+1F9DC"},
        {"name": "Elf", "symbol": "🧝", "unicode": "U+1F9DD"},
        {"name": "Genie", "symbol": "🧞", "unicode": "U+1F9DE"},
        {"name": "Zombie", "symbol": "🧟", "unicode": "U+1F9DF"},
        {"name": "Sponge", "symbol": "🧽", "unicode": "U+1F9FD"},
        {"name": "Drop of Blood", "symbol": "🩸", "unicode": "U+1FA78"},
        {"name": "Bandage", "symbol": "🩹", "unicode": "U+1FA79"},
        {"name": "Stethoscope", "symbol": "🩺", "unicode": "U+1FA7A"},
        {"name": "Crutch", "symbol": "🩼", "unicode": "U+1FA7C"},
        {"name": "X-Ray", "symbol": "🩻", "unicode": "U+1FA7B"},
        {"name": "Yo-Yo", "symbol": "🪀", "unicode": "U+1FA80"},
        {"name": "Kite", "symbol": "🪁", "unicode": "U+1FA81"},
        {"name": "Ring Buoy", "symbol": "🛟", "unicode": "U+1F6DF"},
        {"name": "Hook", "symbol": "🪝", "unicode": "U+1FA9D"},
        {"name": "Hamsa", "symbol": "🪬", "unicode": "U+1FAAC"},
        {"name": "Nazar Amulet", "symbol": "🧿", "unicode": "U+1F9FF"},
        {"name": "Mendhi", "symbol": "🪔", "unicode": "U+1FA94"},
        {"name": "Comet", "symbol": "☄️", "unicode": "U+2604"},
        {"name": "Ringed Planet", "symbol": "🪐", "unicode": "U+1FA90"},
        {"name": "Glowing Star", "symbol": "🌟", "unicode": "U+1F31F"},
        {"name": "Shooting Star", "symbol": "🌠", "unicode": "U+1F320"},
        {"name": "Milky Way", "symbol": "🌌", "unicode": "U+1F30C"},
        {"name": "Sun Behind Cloud", "symbol": "⛅", "unicode": "U+26C5"},
        {"name": "Cloud with Lightning", "symbol": "🌩️", "unicode": "U+1F329"},
        {"name": "Tornado", "symbol": "🌪️", "unicode": "U+1F32A"},
        {"name": "Fog", "symbol": "🌫️", "unicode": "U+1F32B"},
        {"name": "Wind Face", "symbol": "🌬️", "unicode": "U+1F32C"},
        {"name": "Closed Umbrella", "symbol": "🌂", "unicode": "U+1F302"},
        {"name": "Umbrella", "symbol": "☂️", "unicode": "U+2602"},
        {"name": "Umbrella with Rain", "symbol": "🌧️", "unicode": "U+1F327"},
        {"name": "Snowman", "symbol": "⛄", "unicode": "U+26C4"},
        {"name": "Snowman without Snow", "symbol": "☃️", "unicode": "U+2603"},
        {"name": "Crystal Ball", "symbol": "🔮", "unicode": "U+1F52E"},
        {"name": "Shopping Cart", "symbol": "🛒", "unicode": "U+1F6D2"},
        {"name": "Parachute", "symbol": "🪂", "unicode": "U+1FA82"},
        {"name": "Speedboat", "symbol": "🚤", "unicode": "U+1F6A4"},
        {"name": "Railway Car", "symbol": "🚃", "unicode": "U+1F683"},
        {"name": "Metro", "symbol": "🚇", "unicode": "U+1F687"},
        {"name": "Light Rail", "symbol": "🚈", "unicode": "U+1F688"},
        {"name": "Station", "symbol": "🚉", "unicode": "U+1F689"},
        {"name": "Bus Stop", "symbol": "🚏", "unicode": "U+1F68F"},
        {"name": "Fuel Pump", "symbol": "⛽", "unicode": "U+26FD"},
        {"name": "Construction", "symbol": "🚧", "unicode": "U+1F6A7"},
        {"name": "Vertical Traffic Light", "symbol": "🚦", "unicode": "U+1F6A6"},
        {"name": "Horizontal Traffic Light", "symbol": "🚥", "unicode": "U+1F6A5"},
        {"name": "Stop Sign", "symbol": "🛑", "unicode": "U+1F6D1"},
    ],
    
    "Flags": [
        {"name": "Checkered Flag", "symbol": "🏁", "unicode": "U+1F3C1"},
        {"name": "Crossed Flags", "symbol": "🎌", "unicode": "U+1F38C"},
        {"name": "Black Flag", "symbol": "🏴", "unicode": "U+1F3F4"},
        {"name": "White Flag", "symbol": "🏳️", "unicode": "U+1F3F3"},
        {"name": "United Kingdom", "symbol": "🇬🇧", "unicode": "U+1F1EC"},
        {"name": "Canada", "symbol": "🇨🇦", "unicode": "U+1F1E8"},
        {"name": "Australia", "symbol": "🇦🇺", "unicode": "U+1F1E6"},
        {"name": "Germany", "symbol": "🇩🇪", "unicode": "U+1F1E9"},
        {"name": "France", "symbol": "🇫🇷", "unicode": "U+1F1EB"},
        {"name": "Spain", "symbol": "🇪🇸", "unicode": "U+1F1EA"},
        {"name": "Italy", "symbol": "🇮🇹", "unicode": "U+1F1EE"},
        {"name": "Japan", "symbol": "🇯🇵", "unicode": "U+1F1EF"},
        {"name": "China", "symbol": "🇨🇳", "unicode": "U+1F1E8"},
        {"name": "India", "symbol": "🇮🇳", "unicode": "U+1F1EE"},
        {"name": "Brazil", "symbol": "🇧🇷", "unicode": "U+1F1E7"},
        {"name": "Russia", "symbol": "🇷🇺", "unicode": "U+1F1F7"},
        {"name": "Mexico", "symbol": "🇲🇽", "unicode": "U+1F1F2"},
        {"name": "South Korea", "symbol": "🇰🇷", "unicode": "U+1F1F0"},
        {"name": "Argentina", "symbol": "🇦🇷", "unicode": "U+1F1E6"},
        {"name": "South Africa", "symbol": "🇿🇦", "unicode": "U+1F1FF"},
        {"name": "Egypt", "symbol": "🇪🇬", "unicode": "U+1F1EA"},
        {"name": "Nigeria", "symbol": "🇳🇬", "unicode": "U+1F1F3"},
        {"name": "Turkey", "symbol": "🇹🇷", "unicode": "U+1F1F9"},
        {"name": "Israel", "symbol": "🇮🇱", "unicode": "U+1F1EE"},
        {"name": "Saudi Arabia", "symbol": "🇸🇦", "unicode": "U+1F1F8"},
        {"name": "UAE", "symbol": "🇦🇪", "unicode": "U+1F1E6"},
        {"name": "Indonesia", "symbol": "🇮🇩", "unicode": "U+1F1EE"},
        {"name": "Thailand", "symbol": "🇹🇭", "unicode": "U+1F1F9"},
        {"name": "Vietnam", "symbol": "🇻🇳", "unicode": "U+1F1FB"},
        {"name": "Philippines", "symbol": "🇵🇭", "unicode": "U+1F1F5"},
        {"name": "Malaysia", "symbol": "🇲🇾", "unicode": "U+1F1F2"},
        {"name": "Singapore", "symbol": "🇸🇬", "unicode": "U+1F1F8"},
        {"name": "Pakistan", "symbol": "🇵🇰", "unicode": "U+1F1F5"},
        {"name": "Bangladesh", "symbol": "🇧🇩", "unicode": "U+1F1E7"},
        {"name": "Sri Lanka", "symbol": "🇱🇰", "unicode": "U+1F1F1"},
        {"name": "Nepal", "symbol": "🇳🇵", "unicode": "U+1F1F3"},
        {"name": "Afghanistan", "symbol": "🇦🇫", "unicode": "U+1F1E6"},
        {"name": "Iran", "symbol": "🇮🇷", "unicode": "U+1F1EE"},
        {"name": "Iraq", "symbol": "🇮🇶", "unicode": "U+1F1EE"},
        {"name": "Syria", "symbol": "🇸🇾", "unicode": "U+1F1F8"},
        {"name": "Jordan", "symbol": "🇯🇴", "unicode": "U+1F1EF"},
        {"name": "Lebanon", "symbol": "🇱🇧", "unicode": "U+1F1F1"},
        {"name": "Palestine", "symbol": "🇵🇸", "unicode": "U+1F1F5"},
        {"name": "Morocco", "symbol": "🇲🇦", "unicode": "U+1F1F2"},
        {"name": "Algeria", "symbol": "🇩🇿", "unicode": "U+1F1E9"},
        {"name": "Tunisia", "symbol": "🇹🇳", "unicode": "U+1F1F9"},
        {"name": "Libya", "symbol": "🇱🇾", "unicode": "U+1F1F1"},
        {"name": "Sudan", "symbol": "🇸🇩", "unicode": "U+1F1F8"},
        {"name": "Ethiopia", "symbol": "🇪🇹", "unicode": "U+1F1EA"},
        {"name": "Kenya", "symbol": "🇰🇪", "unicode": "U+1F1F0"},
        {"name": "Uganda", "symbol": "🇺🇬", "unicode": "U+1F1FA"},
        {"name": "Tanzania", "symbol": "🇹🇿", "unicode": "U+1F1F9"},
        {"name": "Zambia", "symbol": "🇿🇲", "unicode": "U+1F1FF"},
        {"name": "Zimbabwe", "symbol": "🇿🇼", "unicode": "U+1F1FF"},
        {"name": "Botswana", "symbol": "🇧🇼", "unicode": "U+1F1E7"},
        {"name": "Namibia", "symbol": "🇳🇦", "unicode": "U+1F1F3"},
        {"name": "Mozambique", "symbol": "🇲🇿", "unicode": "U+1F1F2"},
        {"name": "Angola", "symbol": "🇦🇴", "unicode": "U+1F1E6"},
        {"name": "Ghana", "symbol": "🇬🇭", "unicode": "U+1F1EC"},
        {"name": "Ivory Coast", "symbol": "🇨🇮", "unicode": "U+1F1E8"},
        {"name": "Senegal", "symbol": "🇸🇳", "unicode": "U+1F1F8"},
        {"name": "Poland", "symbol": "🇵🇱", "unicode": "U+1F1F5"},
        {"name": "Ukraine", "symbol": "🇺🇦", "unicode": "U+1F1FA"},
        {"name": "Romania", "symbol": "🇷🇴", "unicode": "U+1F1F7"},
        {"name": "Greece", "symbol": "🇬🇷", "unicode": "U+1F1EC"},
        {"name": "Portugal", "symbol": "🇵🇹", "unicode": "U+1F1F5"},
        {"name": "Netherlands", "symbol": "🇳🇱", "unicode": "U+1F1F3"},
        {"name": "Belgium", "symbol": "🇧🇪", "unicode": "U+1F1E7"},
        {"name": "Austria", "symbol": "🇦🇹", "unicode": "U+1F1E6"},
        {"name": "Switzerland", "symbol": "🇨🇭", "unicode": "U+1F1E8"},
        {"name": "Denmark", "symbol": "🇩🇰", "unicode": "U+1F1E9"},
        {"name": "Sweden", "symbol": "🇸🇪", "unicode": "U+1F1F8"},
        {"name": "Norway", "symbol": "🇳🇴", "unicode": "U+1F1F3"},
        {"name": "Finland", "symbol": "🇫🇮", "unicode": "U+1F1EB"},
        {"name": "Iceland", "symbol": "🇮🇸", "unicode": "U+1F1EE"},
        {"name": "Ireland", "symbol": "🇮🇪", "unicode": "U+1F1EE"},
        {"name": "Scotland", "symbol": "🏴󠁧󠁢󠁳󠁣󠁴󠁿", "unicode": "U+1F3F4"},
        {"name": "Wales", "symbol": "🏴󠁧󠁢󠁷󠁬󠁳󠁿", "unicode": "U+1F3F4"},
        {"name": "Hungary", "symbol": "🇭🇺", "unicode": "U+1F1ED"},
        {"name": "Czech Republic", "symbol": "🇨🇿", "unicode": "U+1F1E8"},
        {"name": "Slovakia", "symbol": "🇸🇰", "unicode": "U+1F1F8"},
        {"name": "Slovenia", "symbol": "🇸🇮", "unicode": "U+1F1F8"},
        {"name": "Croatia", "symbol": "🇭🇷", "unicode": "U+1F1ED"},
        {"name": "Serbia", "symbol": "🇷🇸", "unicode": "U+1F1F7"},
        {"name": "Bulgaria", "symbol": "🇧🇬", "unicode": "U+1F1E7"},
        {"name": "New Zealand", "symbol": "🇳🇿", "unicode": "U+1F1F3"},
        {"name": "Cambodia", "symbol": "🇰🇭", "unicode": "U+1F1F0"},
        {"name": "Laos", "symbol": "🇱🇦", "unicode": "U+1F1F1"},
        {"name": "Myanmar", "symbol": "🇲🇲", "unicode": "U+1F1F2"},
        {"name": "Mongolia", "symbol": "🇲🇳", "unicode": "U+1F1F2"},
        {"name": "Hong Kong", "symbol": "🇭🇰", "unicode": "U+1F1ED"},
        {"name": "Taiwan", "symbol": "🇹🇼", "unicode": "U+1F1F9"},
        {"name": "North Korea", "symbol": "🇰🇵", "unicode": "U+1F1F0"},
        {"name": "Colombia", "symbol": "🇨🇴", "unicode": "U+1F1E8"},
        {"name": "Venezuela", "symbol": "🇻🇪", "unicode": "U+1F1FB"},
        {"name": "Peru", "symbol": "🇵🇪", "unicode": "U+1F1F5"},
        {"name": "Chile", "symbol": "🇨🇱", "unicode": "U+1F1E8"},
        {"name": "Ecuador", "symbol": "🇪🇨", "unicode": "U+1F1EA"},
        {"name": "Bolivia", "symbol": "🇧🇴", "unicode": "U+1F1E7"},
        {"name": "Paraguay", "symbol": "🇵🇾", "unicode": "U+1F1F5"},
        {"name": "Uruguay", "symbol": "🇺🇾", "unicode": "U+1F1FA"},
        {"name": "Guatemala", "symbol": "🇬🇹", "unicode": "U+1F1EC"},
        {"name": "Honduras", "symbol": "🇭🇳", "unicode": "U+1F1ED"},
        {"name": "Nicaragua", "symbol": "🇳🇮", "unicode": "U+1F1F3"},
        {"name": "Costa Rica", "symbol": "🇨🇷", "unicode": "U+1F1E8"},
        {"name": "Panama", "symbol": "🇵🇦", "unicode": "U+1F1F5"},
        {"name": "Cuba", "symbol": "🇨🇺", "unicode": "U+1F1E8"},
        {"name": "Dominican Republic", "symbol": "🇩🇴", "unicode": "U+1F1E9"},
        {"name": "Jamaica", "symbol": "🇯🇲", "unicode": "U+1F1EF"},
        {"name": "Puerto Rico", "symbol": "🇵🇷", "unicode": "U+1F1F5"},
        {"name": "Trinidad Tobago", "symbol": "🇹🇹", "unicode": "U+1F1F9"},
        # Additional emojis to reach 800+
        {"name": "Antigua Barbuda", "symbol": "🇦🇬", "unicode": "U+1F1E6"},
        {"name": "Barbados", "symbol": "🇧🇧", "unicode": "U+1F1E7"},
        {"name": "Dominica", "symbol": "🇩🇲", "unicode": "U+1F1E9"},
        {"name": "Grenada", "symbol": "🇬🇩", "unicode": "U+1F1EC"},
        {"name": "Saint Kitts Nevis", "symbol": "🇰🇳", "unicode": "U+1F1F0"},
        {"name": "Saint Lucia", "symbol": "🇱🇨", "unicode": "U+1F1F1"},
        {"name": "Saint Vincent Grenadines", "symbol": "🇻🇨", "unicode": "U+1F1FB"},
        {"name": "Bahamas", "symbol": "🇧🇸", "unicode": "U+1F1E7"},
        {"name": "Belize", "symbol": "🇧🇿", "unicode": "U+1F1E7"},
        {"name": "Haiti", "symbol": "🇭🇹", "unicode": "U+1F1ED"},
        {"name": "Guyana", "symbol": "🇬🇾", "unicode": "U+1F1EC"},
        {"name": "Suriname", "symbol": "🇸🇷", "unicode": "U+1F1F8"},
        {"name": "Falkland Islands", "symbol": "🇫🇰", "unicode": "U+1F1EB"},
        {"name": "French Guiana", "symbol": "🇬🇫", "unicode": "U+1F1EC"},
        {"name": "South Georgia", "symbol": "🇬🇸", "unicode": "U+1F1EC"},
        {"name": "South Sandwich Islands", "symbol": "🇸🇸", "unicode": "U+1F1F8"},
    ]
}


class EmojiService:
    """WhatsApp-style emoji service with full UTF-8 support"""
    
    def __init__(self):
        self.categories = EMOJI_CATEGORIES
        self._emoji_index = self._build_emoji_index()
    
    def _build_emoji_index(self) -> Dict[str, Dict[str, Any]]:
        """Build a searchable index of all emojis"""
        index = {}
        for category, emojis in self.categories.items():
            for emoji in emojis:
                index[emoji["symbol"]] = {
                    "name": emoji["name"],
                    "category": category,
                    "unicode": emoji["unicode"],
                    "symbol": emoji["symbol"]  # Add symbol to index
                }
        return index
    
    def get_all_emojis(self) -> List[Dict[str, Any]]:
        """Get all emojis in WhatsApp-style format"""
        result = []
        for category, emojis in self.categories.items():
            result.append({
                "category": category,
                "emojis": emojis
            })
        return result
    
    def get_emojis_by_category(self, category: str) -> List[Dict[str, Any]]:
        """Get emojis for a specific category"""
        return self.categories.get(category, [])
    
    def search_emojis(self, query: str) -> List[Dict[str, Any]]:
        """Search emojis by name or symbol"""
        query = query.lower()
        results = []
        
        for category, emojis in self.categories.items():
            matching = [
                emoji for emoji in emojis 
                if query in emoji["name"].lower() or query in emoji["symbol"]
            ]
            if matching:
                results.append({
                    "category": category,
                    "emojis": matching
                })
        
        return results
    
    def get_emoji_info(self, symbol: str) -> Optional[Dict[str, Any]]:
        """Get detailed information about an emoji"""
        return self._emoji_index.get(symbol)
    
    def validate_emoji(self, symbol: str) -> bool:
        """Check if an emoji symbol is supported"""
        return symbol in self._emoji_index
    
    def get_popular_emojis(self, limit: int = 20) -> List[Dict[str, Any]]:
        """Get frequently used emojis"""
        popular_symbols = ["😀", "😂", "❤️", "👍", "🙏", "😊", "🔥", "💯", 
                          "😎", "🥰", "😍", "🤔", "🤣", "✨", "🎉", "💕", "👌", 
                          "😘", "💙", "🥺"]
        
        result = []
        for symbol in popular_symbols[:limit]:
            info = self.get_emoji_info(symbol)
            if info:
                result.append({
                    "symbol": symbol,
                    "name": info["name"],
                    "category": info["category"],
                    "unicode": info["unicode"]
                })
        
        return result


# Global emoji service instance
emoji_service = EmojiService()


def get_emoji_service() -> EmojiService:
    """Get the global emoji service instance"""
    return emoji_service
